name: CI

on:
  push:
  schedule:
  # 定时任务
    - cron: '0 6 * * *'
jobs:
    build-server:
        name: Build Mix-Space(server)
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v2
        - name: Setup Node.js environment
          uses: actions/setup-node@v2.1.4
        - name: Build server
          run: |
            git clone https://github.com/mx-space/server
            sudo npm install rimraf -g
            cd server
            sudo yarn
            sudo rm -rf .env
            sudo wget http://api.iucky.cn/themes/.env_server
            sudo mv .env_server .env
            echo "fix user files success"
            sudo yarn build
            cd ..
            
        - name: tar file
          run: |
            tar cf server.tar.gz *
            mv server.tar.gz ..
            cd ..
            sudo rm -rf server
        - name: Git Commit and Push
          uses: github-actions-x/commit@v2.6
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            commit-message: Bot Build
            email:  1596355173@qq.com
            name: wibus-wee
    build-kami:
        name: Build Mix-Space(kami)
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v2
        - name: Setup Node.js environment
          uses: actions/setup-node@v2.1.4
        - name: Build kami
          run: |
            git clone https://github.com/mx-space/kami
            sudo npm install rimraf -g
            cd kami
            sudo yarn
            sudo  rm -rf .env
            sudo  rm -rf config.ts
            sudo  wget http://api.iucky.cn/themes/kami/.env
            sudo  wget http://api.iucky.cn/themes/kami/configs.ts
            cd public
            sudo  rm -rf manifest.json
            sudo  wget http://api.iucky.cn/themes/kami/manifest.json
            cd ..
            echo "fix user files success"
            sudo yarn build
        - name: tar file
          run: |
            tar cf kami.tar.gz *
            mv kami.tar.gz ..
            cd ..
            sudo rm -rf kami
        - name: Git Commit and Push
          uses: github-actions-x/commit@v2.6
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            commit-message: Bot Build
            email:  1596355173@qq.com
            name: wibus-wee
    build-admin:
        name: Build Mix-Space(admin)
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v2
        - name: Setup Node.js environment
          uses: actions/setup-node@v2.1.4
        - name: Build admin
          run: |
            git clone https://github.com/mx-space/admin
            sudo npm install rimraf -g
            cd admin
            sudo yarn
            sudo rm -rf .env
            sudo rm -rf vue.config.js
            sudo wget http://api.iucky.cn/themes/admin/.env
            sudo wget http://api.iucky.cn/themes/admin/vue.config.js
            echo "fix user files success"
            sudo yarn build
        - name: tar file
          run: |
            tar cf admin.tar.gz /dist/*
            mv admin.tar.gz ..
            cd ..
            sudo rm -rf admin
        - name: Git Commit and Push
          uses: github-actions-x/commit@v2.6
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            commit-message: Bot Build
            email:  1596355173@qq.com
            name: wibus-wee
