name: Builder

on:
  push:
  schedule:
  # 定时任务
    - cron: '0 6 * * *'
jobs:
    build-server:
        name: Build Mix-Space(all)
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v2
        - name: Setup Node.js environment
          uses: actions/setup-node@v2.1.4
        - name: Build server
          run: |
            git clone https://github.com/mx-space/server
            sudo npm install rimraf -g
            cd server
            sudo yarn
            sudo rm -rf .env
            sudo wget http://api.iucky.cn/themes/.env_server
            sudo mv .env_server .env
            echo "fix user files success"
            sudo yarn build
            cd ..
        - name: Build kami
          run: |
            git clone https://github.com/mx-space/kami
            sudo npm install rimraf -g
            cd kami
            sudo yarn
            sudo  rm -rf .env
            sudo  rm -rf config.ts
            sudo  wget http://api.iucky.cn/themes/kami/.env
            sudo  wget http://api.iucky.cn/themes/kami/configs.ts
            cd public
            sudo  rm -rf manifest.json
            sudo  wget http://api.iucky.cn/themes/kami/manifest.json
            cd ..
            echo "fix user files success"
            sudo yarn build
            cd .. 
        - name: Build admin
          run: |
            git clone https://github.com/mx-space/admin
            sudo npm install rimraf -g
            cd admin
            sudo yarn
            sudo rm -rf .env
            sudo rm -rf vue.config.js
            sudo wget http://api.iucky.cn/themes/admin/.env
            sudo wget http://api.iucky.cn/themes/admin/vue.config.js
            echo "fix user files success"
            sudo yarn build
        - name: ls things
          run: ls
        - name: tar file
          run: |
            sudo tar cf kami.tar.gz kami
            sudo tar cf server.tar.gz server
            sudo tar cf admin.tar.gz admin
        - name: Delete
          run: |
            sudo rm -rf kami
            sudo rm -rf server
            sudo rm -rf admin
	- name: Git Commit and Push
          uses: github-actions-x/commit@v2.6
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            commit-message: Bot Build
            email:  1596355173@qq.com
            name: wibus-wee
