name: Builder V1.0

on:
  push:
  schedule:
  # 定时任务
    - cron: '0 6 * * *'
jobs:
    build-server:
        name: Build Mix-Space(server)
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v2
        - name: Setup Node.js environment
          uses: actions/setup-node@v2.1.4
        - name: Build server
          run: |
            git clone https://github.com/mx-space/server
            sudo npm install rimraf -g
            cd server
            sudo yarn
            sudo rm -rf .env
            sudo mv ../server_config/.env .env
            echo "成功填入用户文件"
            sudo yarn build
            cd ..
        - name: Upload server Build Artifact
          uses: actions/upload-artifact@v2.2.2
          with:
            name: Mix-Space_Server
            path: ./server

    build-kami:
        name: Build Mix-Space(kami)
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v2
        - name: Setup Node.js environment
          uses: actions/setup-node@v2.1.4
        - name: Build kami
          run: |
            git clone https://github.com/mx-space/kami
            sudo npm install rimraf -g
            cd kami
            sudo yarn
            sudo  rm -rf .env
            sudo  rm -rf config.ts
            sudo mv ../kami_config/.env .env
            sudo mv ../kami_config/configs.ts configs.ts
            sudo mv ../kami_config/manifest.json manifest.json
            cd public
            sudo rm -rf manifest.json
            sudo mv ../manifest.json manifest.json
            cd ..
            echo "成功填入用户文件"
            sudo yarn build
        - name: Upload kami Build Artifact
          uses: actions/upload-artifact@v2.2.2
          with:
            name: Mix-Space_Kami
            path: ./kami

    build-admin:
        name: Build Mix-Space(admin)
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v2
        - name: Setup Node.js environment
          uses: actions/setup-node@v2.1.4
        - name: Build admin
          run: |
            git clone https://github.com/mx-space/admin
            sudo npm install rimraf -g
            cd admin
            sudo yarn
            sudo rm -rf .env
            sudo rm -rf vue.config.js
            sudo mv ../admin_config/.env .env
            sudo mv ../admin_config/vue.config.js vue.config.js
            echo "成功填入用户文件"
            sudo yarn build
        - name: Upload admin Build Artifact
          uses: actions/upload-artifact@v2.2.2
          with:
            name: Mix-Space_Admin
            path: ./admin/dist
