name: Builder

on:
  push:
  schedule:
  # 定时任务
    - cron: '0 6 * * *'
jobs:
    build-server:
        name: Build Mix-Space(server)
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
          with:
            persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
            fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
        - name: checkout
          uses: actions/checkout@v2
        - name: Setup Node.js environment
          uses: actions/setup-node@v2.1.4
        - name: Build server
          run: |
            git clone https://github.com/mx-space/server
            sudo npm install rimraf -g
            cd server
            sudo yarn
            sudo rm -rf .env
            sudo wget http://api.iucky.cn/themes/.env_server
            sudo mv .env_server .env
            echo "fix user files success"
            sudo yarn build
            cd ..
        - name: Commit files
          run: |
            git config --local user.email "1596355173@qq.com"
            git config --local user.name "wibus-wee"
            git add .
            git commit -m "Add changes" -a
        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
    build-kami:
        name: Build Mix-Space(kami)
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v2
        - name: Setup Node.js environment
          uses: actions/setup-node@v2.1.4
        - name: Build kami
          run: |
            git clone https://github.com/mx-space/kami
            sudo npm install rimraf -g
            cd kami
            sudo yarn
            sudo  rm -rf .env
            sudo  rm -rf config.ts
            sudo  wget http://api.iucky.cn/themes/kami/.env
            sudo  wget http://api.iucky.cn/themes/kami/configs.ts
            cd public
            sudo  rm -rf manifest.json
            sudo  wget http://api.iucky.cn/themes/kami/manifest.json
            cd ..
            echo "fix user files success"
            sudo yarn build
        - name: Commit files
          run: |
            git config --local user.email "1596355173@qq.com"
            git config --local user.name "wibus-wee"
            git add .
            git commit -m "Add changes" -a
        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
    build-admin:
        name: Build Mix-Space(admin)
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v2
        - name: Setup Node.js environment
          uses: actions/setup-node@v2.1.4
        - name: Build admin
          run: |
            git clone https://github.com/mx-space/admin
            sudo npm install rimraf -g
            cd admin
            sudo yarn
            sudo rm -rf .env
            sudo rm -rf vue.config.js
            sudo wget http://api.iucky.cn/themes/admin/.env
            sudo wget http://api.iucky.cn/themes/admin/vue.config.js
            echo "fix user files success"
            sudo yarn build
        - name: Upload admin Build Artifact
          uses: actions/upload-artifact@v2.2.2
          with:
            name: Mix-Space_Admin
            path: ./admin/dist
